### ISSUE TITLE
Module not found: Can't resolve

### ISSUE THREAD

**Issue by xxleyi** [ericclemmons/click-to-component#37] opened 2022-04-28 13:40 UTC
`Module not found: Can't resolve 'click-to-react-component'`

I am trying this awesome tool, but can not use it as a package. For now, I put src files in my components folder. 

If I try import from package directly, I will meet resolve error like above.

Don't know why, seems others do not have this problem.

My webpack is `webpack@4.46.0`

**Comment by ericclemmons** [comment] 2022-04-28 21:46
What's your webpack config?  Does it resolve `.mjs` files?

You can fork the repo and put it in https://github.com/ericclemmons/click-to-component/tree/main/apps as a PR & I'll help troubleshoot it.

**Comment by ericclemmons** [comment] 2022-04-29 19:25
Got it!  I'll go ahead & close this then – to support `webpack` (which powered Next.js & CRA), we'd at least need a reproducible sample under `/apps` to work off of.

**Closed by ericclemmons** 2022-04-29 19:25 UTC
Labels: enhancement

**Comment by fhourdin** [comment] 2022-05-04 09:48
Hi ! Same issue for me, I managed to make the lib works by adding `"main": "./src/index.js"` in package.json.
Looks like the "exports" alternative is not working for me for some reasons.
Node 16.14.2
Webpack 5.72.0
